version: '3.7'

services:
  xx-server-postgres:
    image: postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  xx-server-adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=pappu687
    ports:
      - 8090:8080
 
  # nest:
  #   container_name: nest
  #   image: node:lts-alpine
  #   working_dir: /var/www
  #   platform: linux/x86_64
  #   command: yarn dev
  #   volumes:
  #     - ./:/var/www:cached
  #   ports:
  #     - 8000:8000
