version: '3.7'

services:
  postgres:
    image: postgres
    volumes:
      - ./server/.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=pappu687
    ports:
      - 8090:8080
 
  nestjs:
    image: node:lts
    working_dir: /var/www
    command: yarn start:dev
    volumes:
      - ./server:/var/www:cached
    ports:
      - 8000:8000

  nextjs:
    image: node:lts-alpine
    working_dir: /var/www
    command: yarn start:dev
    volumes:
      - ./client:/var/www:cached
    ports:
      - 18888:18888
